name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base

    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics | tee flake8_errors.log
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics | tee flake8_warnings.log

    - name: Test with pytest
      run: |
        conda install pytest
        pytest | tee pytest_output.log

    - name: Upload flake8 errors
      uses: actions/upload-artifact@v3
      with:
        name: flake8-errors
        path: flake8_errors.log

    - name: Upload flake8 warnings
      uses: actions/upload-artifact@v3
      with:
        name: flake8-warnings
        path: flake8_warnings.log

    - name: Upload pytest output
      uses: actions/upload-artifact@v3
      with:
        name: pytest-output
        path: pytest_output.log
